---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: tcproutes.specs.smi-spec.io
spec:
  group: specs.smi-spec.io
  scope: Namespaced
  names:
    kind: TCPRoute
    shortNames:
      - tr
    plural: tcproutes
    singular: tcproute
  versions:
    - name: v1alpha4
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - matches
              properties:
                matches:
                  description: Match conditions of this route.
                  type: object
                  required:
                    - ports
                  properties:
                    ports:
                      description: Port numbers to match TCP traffic.
                      type: array
                      items:
                        type: integer
